### 1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.
Delete the found duplicate file.
[Hint: use hashlib]

In [3]:
import hashlib
import os
directory=[]
dirpath="C:/Users/dparasher/OneDrive - ALLEGIS GROUP/Desktop/file"


for(dir_path,dir_names,file_name) in os.walk(dirpath):
    directory.extend(file_name)

hashes = {}
result = set()
for i in range(len(directory)):
    fileObj = open('C:/Users/dparasher/OneDrive - ALLEGIS GROUP/Desktop/file/'+directory[i],'r')
    content = fileObj.read()
    content=str(content)

    message = hashlib.sha256()
    message.update(bytes(content, 'utf-8'))
    hashcode=message.hexdigest()

    if hashcode in hashes.keys():
        result.add(hashes[hashcode])
        result.add(directory[i])

    else:
        hashes[hashcode]=directory[i]

print("All files in the directory: ", os.listdir("C:/Users/dparasher/OneDrive - ALLEGIS GROUP/Desktop/file"))
print("Files wih same content are: ", result)

All files in the directory:  ['c1.txt', 'c2.txt', 'c3.txt', 'c4.txt', 'c5.txt']
Files wih same content are:  {'c3.txt', 'c2.txt', 'c1.txt'}


### 2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]

In [4]:
import random
import string

characters = string.ascii_letters + string.digits + string.punctuation
password = ''.join(random.choice(characters) for i in range(6))
print("Password:", password)

Password: "R%OnS


### 3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [23]:
import numpy as np

# mat=np.ones((4,4), dtype='int64')
#
# b=1
# for i in range(0,4):
#     for j in range(0,4):
#         mat[i][j]=b
#         b+=1
# print(mat)
#
# flag=False
#
# for i in range(4):
#     for j in range(4):
#         num=mat[i][j]
#         if num==1:
#             mat[i][j]=1
#         elif num>1:
#             for k in range(2, num):
#                 if(num%i)==0:
#                     mat[i][j]=num
#                     flag=True
#                     break
#                 else:
#                     mat[i][j]=num*num*num

# import numpy as np
# import math
# def isPrime(num):
#
#     for i in range(2,int(math.sqrt(num))+1):
#         if num%2==0:
#             return False;
#
#     return True;
#
# #Taking input
# rows = int(input("Enter number of rows"))
# cols = int(input("Enter number of columns"))
#
# # declaring array with ones
# arr = np.ones((rows,cols),'float')
#
# # initialise array with user values
#
# for i in range(rows):
#     for j in range(cols):
#         arr[i][j] = int(input("Enter the element"))
#
#
# # replace prime number by cube of the number
# position=-1
# for i in range(rows):
#     for j in range(cols):
#         position+=1
#         if isPrime(position):
#             arr[i][j] = arr[i][j]*arr[i][j]*arr[i][j]
#
# print(mat)


import numpy as np
import math
def isPrime(n):
    for i in range(2,(n//2)+1):
        if n%i==0:
            return False
    return True

l=[[1,2,3],
  [4,5,6],
  [7,8,9]]
s=int(len(l))
arr=np.array(l).reshape(s,s)
print('Origial array:-')
print(arr)

for i in range(s):
    for j in range(s):
        xx=i*s+j
        x=arr[i][j]
        arr[i][j]=x*x*x if isPrime(xx) else x

print('\nModified array:-')
print(arr)

Origial array:-
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified array:-
[[  1   8  27]
 [ 64   5 216]
 [  7 512   9]]


### 4.	Python program to get the sum of every cubed value and its previous integer.

In [13]:
l=[[1,2,3],
  [4,5,6],
  [7,8,9]]
s=int(len(l))
arr=np.array(l).reshape(s,s)

def isCube(n):
    if n**(1/3)==abs(n**(1/3)):
        return True
    return False
ans=0
for i in range(s):
    for j in range(s):
        ans+=arr[i][j] if isCube(arr[i][j]) else 0
print(ans)

45


### 5.	Given two arrays, find their intersection. Examples:

Input:  arr1[] = [1, 3, 4, 5, 7]
             arr2[] = [2, 3, 5, 6]


In [14]:
import numpy as np
arr1=np.array([1,3,4,5,7])
arr2=np.array([2,3,5,6])

res=np.intersect1d(arr1, arr2)
print(res)

[3 5]


### 6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [15]:
import numpy as np

mat=np.ones((7,7), dtype='int64')

mul=1
# for i in range(0,7):
#     for j in range(0,7):
#         mat[i][j]=mul
#         mul+=1
#         mat[i][j]=mul*7

# mat2=np.ones((7,7), dtype='int8')
# new_mat2=np.multiply(mat2,7)

# print(mat, '\n')
# for i in range(0,7):
#     for j in range(0,7):
#         mat[i][j]*=7

# res= np.empty(shape=(7,7), dtype='int8')
# for i in range(0,7):
#     for j in range(0,7):
#         res[i][j]=mat[i][j]+new_mat2[i][j]


# new_mul=np.multiply(mat,7)
# print(res, '\n')
# print(mat)
for i in range(7):
    for j in range(7):
        if i==0 and j==0:
            mat[0][0]=7
            mul+=1
        else:
            mat[i][j]=7*mul
            mul+=1

print(mat)
print('\nLast element of the matrix: ', mat[6][6])

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]

Last element of the matrix:  343


### 7.	Checker Board Patten using Numpy:
[   1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1  ]


In [21]:
x = np.ones((7, 5), dtype='int8')
x[1::2, ::2] = 0
x[::2, 1::2] = 0
print(x)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


### 8.	Create a given Matrix:
[  A,     B,     C,       D
   E,      F,     G,       H
    I,      a,      K,       L
   M,    N,     o,       P
   Q,     R,      S,       T
   U,     0,     W,      O ]

Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan
Return the count of the missing values


In [20]:
arr = [['A','B','C','D'],
       ['E','F','G','H'],
       ['I','a','K','L'],
       ['M','N','o','P'],
       ['Q','R','S','T'],
       ['U','0','W','O']]
counter=0

for i in range(len(arr)):
    for j in range(len(arr[0])):
        if arr[i][j]=='A' or arr[i][j]=='E' or arr[i][j]=='I' or arr[i][j]=='O' or arr[i][j]=='U'or arr[i][j] =='a' or arr[i][j]=='e' or arr[i][j]=="i" or arr[i][j]=='o' or arr[i][j]=='u':
            arr[i][j]=np.nan
            counter+=1


print('Given array\n', arr)
print("\nNumber of vowels are = ",counter)

Given array
 [[nan, 'B', 'C', 'D'], [nan, 'F', 'G', 'H'], [nan, nan, 'K', 'L'], ['M', 'N', nan, 'P'], ['Q', 'R', 'S', 'T'], [nan, '0', 'W', nan]]

Number of vowels are =  7
